from .DesktopNotificationConfig import DesktopNotificationConfig
from .DesktopScheduleNotificationConfig import DesktopScheduleNotificationConfig

__all__ = ["DesktopNotificationConfig", "DesktopScheduleNotificationConfig"]